# services
services:
  app:
    image: app:user
    container_name: app
    build: requirements/app
    depends_on: # insures that wordpress service starts before Nginx
      - vault 
    networks:
      - Transcendence
    restart: always
    volumes:
          - vault-file:/vault
          - database:/app/database/
 #nginx
  nginx:
    image: owasp/modsecurity-crs:nginx
    container_name: nginx
    user: root
    env_file:
      - .env
    ports: # port binding 442 on the host to 443 on the container
      - "443:8843"
    depends_on: # insures that wordpress service starts before Nginx
      - app 
    networks:
      - Transcendence 
    restart: always
    volumes:
      - ./requirements/nginxModSec/log/modsec_audit.log:/var/log/modsec_audit.log # bind mount the volume to the container
  
  # grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - Transcendence
    volumes:
      - ./requirements/grafana/config/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./requirements/grafana/config/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./requirements/grafana/config/dashboards/:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1234  # 👈 Grafana will auto-set this on first startup
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/requests_count.json  # Prometheuscompo

  prometheus:
    image: 'ubuntu/prometheus'
    container_name: prometheus
    ports: 
      - 9090:9090
    depends_on: # insures that wordpress service starts before Nginx
      - app 
    networks:
      - Transcendence
    volumes:
      - ./requirements/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml

  # vault
  vault:
    image: vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_LOCAL_CONFIG: |
        {
          "storage": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": [{
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": true
            }
          }],
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h",
          "ui": true
        }
      VAULT_ADDR: 'http://localhost:8200'
      ROOT_TOKEN: 'root-token' 
    cap_add:
      - IPC_LOCK
    volumes:
          - vault-file:/vault
    networks:
      - Transcendence

volumes:
  vault-file:
    name: vault-file 
    driver: local
    driver_opts:
      device: /home/${USER}/volume/vault # To change in case I change laptop
      o : bind
      type : none
  database:
    name: database
    driver: local
    driver_opts:
      device: /home/${USER}/volume/database # To change in case I change laptop
      o : bind
      type : none

networks:
  Transcendence:
    name: Transcendence 

