global:
  scrape_interval: 15s

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - 'alertmanager:9093'  # Container name + port (default)

rule_files:
  - 'alert.rules.yml'  
  
scrape_configs:
  - job_name: app 
    static_configs:
      - targets: ["app:3000"]
  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]
