
# Pull nodejs image form dockerHub
FROM node:22.14.0

# enter directory
WORKDIR /app

# Copy everything in host current dir to the WORDIR
COPY . .

# install jq, update, upgrade
RUN apt update && apt upgrade -y \
    && apt install -y jq

# update to latest version
RUN npm update -g npm

# Install all dependencies
RUN npm install

#Copy startup script
COPY entrypoint.sh /entrypoint.sh

# set script as and executable
RUN chmod +x /entrypoint.sh

# run the script with sh and make the env changes persistent, then launch the server
CMD ["/bin/sh", "-c", ". /entrypoint.sh && exec npm run dev"]
