{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Time Spent ",
   "type": "timeseries",
   "description": "Total CPU time spent in each mode (user, system, idle, iowait)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{cpu=\"8\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests durations by bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{status_code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{status_code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}